services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: alpha_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d alpha_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./alpha-api
    env_file:
      - ./alpha-api/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8000"  # host:container
    volumes:
      - ./alpha-api/app:/app/app
