services:
  api:
    build:
      context: ./alpha-api
    env_file:
      - ./alpha-api/.env
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - ./alpha-api/app:/app/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
